services:
  app:
    build: .
    ports:
      - "3005:3000"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-bitcoin_tracker}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
      - COINDESK_API_KEY=${COINDESK_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-bitcoin_tracker}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
